/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.busUIPanels;

import java.awt.Color;
import javax.swing.JFrame;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bus.Bus;
import mysql.util.MySQLUtil;

/**
 *
 * @author slenk
 */
public class AddBusDetails extends javax.swing.JFrame {

    /**
     * Creates new form AddBusDetails
     */
    public AddBusDetails() {
        initComponents();
        
        panelTitle.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.4f));
        lblTitle.setForeground(Color.WHITE);
        lblDepartureDetails.setForeground(Color.WHITE);
        lblArrivalDetails.setForeground(Color.WHITE);
        lblDepartureCity.setForeground(Color.WHITE);
        lblArrivalCity.setForeground(Color.WHITE);
        lblDepartureTime.setForeground(Color.WHITE);
        lblArrivalTime.setForeground(Color.WHITE);
        lblDepartureBusStn.setForeground(Color.WHITE);
        lblArrivalBusStn.setForeground(Color.WHITE);
        lblDepartBusTer.setForeground(Color.WHITE);
        lblArrivalBusTer.setForeground(Color.WHITE);
        lblBusCompany.setForeground(Color.WHITE);
        lblSeats.setForeground(Color.WHITE);
        lblPrice.setForeground(Color.WHITE);
        lblDuration.setForeground(Color.WHITE);
        lblMiles.setForeground(Color.WHITE);
        departPanel.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.6f));
        arrivalPanel.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.6f));
        
//        txtDepartureCity.setBorder(BorderFactory.createTitledBorder("Departure City"));
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        populateTableBusDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel() {
            public void paintComponent(Graphics g) {

                ImageIcon im = new ImageIcon("D:\\My NEU Assignments\\AED Final Project\\git\\AED_Final_Project\\AED_Final_Project\\src\\assets\\bus-dashboard-bg.jpg");

                Image i = im.getImage();

                g.drawImage(i, 0, 0, this.getSize().width,
                    this.getSize().height, this);
            }
        };
        departPanel = new javax.swing.JPanel();
        lblDepartureDetails = new javax.swing.JLabel();
        lblDepartureCity = new javax.swing.JLabel();
        lblDepartureTime = new javax.swing.JLabel();
        lblDepartureBusStn = new javax.swing.JLabel();
        lblDepartBusTer = new javax.swing.JLabel();
        lblBusCompany = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtDepartureTime = new javax.swing.JTextField();
        txtDepartureCity = new javax.swing.JTextField();
        txtDepartBusStn = new javax.swing.JTextField();
        txtDepartBusTer = new javax.swing.JTextField();
        txtBusCompany = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        arrivalPanel = new javax.swing.JPanel();
        lblArrivalDetails = new javax.swing.JLabel();
        lblArrivalCity = new javax.swing.JLabel();
        lblArrivalTime = new javax.swing.JLabel();
        lblArrivalBusStn = new javax.swing.JLabel();
        lblArrivalBusTer = new javax.swing.JLabel();
        txtArrivalCity = new javax.swing.JTextField();
        txtArrivalTime = new javax.swing.JTextField();
        txtArrivalBusStn = new javax.swing.JTextField();
        txtArrivalBusTer = new javax.swing.JTextField();
        lblDuration = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        lblMiles = new javax.swing.JLabel();
        txtMiles = new javax.swing.JTextField();
        btnUpdateBusDetails = new javax.swing.JButton();
        btnDeleteBusDetails = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnAddBusDetails = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        busTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        departPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblDepartureDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDepartureDetails.setText("DEPARTURE DETAILS");

        lblDepartureCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDepartureCity.setText("Departure City");

        lblDepartureTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDepartureTime.setText("Departure Time");

        lblDepartureBusStn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDepartureBusStn.setText("Departure Bus Station");

        lblDepartBusTer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDepartBusTer.setText("Departure Bus Terminal");

        lblBusCompany.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBusCompany.setText("Bus Company Name");

        lblSeats.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSeats.setText("Seats");

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrice.setText("Price");

        javax.swing.GroupLayout departPanelLayout = new javax.swing.GroupLayout(departPanel);
        departPanel.setLayout(departPanelLayout);
        departPanelLayout.setHorizontalGroup(
            departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(departPanelLayout.createSequentialGroup()
                        .addGroup(departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDepartureDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(departPanelLayout.createSequentialGroup()
                                .addGroup(departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDepartureBusStn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBusCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDepartureCity, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDepartBusTer, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDepartureCity, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDepartBusStn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDepartBusTer, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBusCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 20, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(departPanelLayout.createSequentialGroup()
                        .addComponent(lblDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        departPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBusCompany, lblDepartBusTer, lblDepartureBusStn, lblDepartureCity, lblDepartureTime, lblPrice, lblSeats});

        departPanelLayout.setVerticalGroup(
            departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDepartureDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartureCity)
                    .addComponent(txtDepartureCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartureTime)
                    .addComponent(txtDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartureBusStn)
                    .addComponent(txtDepartBusStn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartBusTer)
                    .addComponent(txtDepartBusTer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusCompany)
                    .addComponent(txtBusCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(departPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrice)
                    .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        departPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBusCompany, lblDepartBusTer, lblDepartureBusStn, lblDepartureCity, lblDepartureTime, lblPrice, lblSeats});

        arrivalPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblArrivalDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArrivalDetails.setText("ARRIVAL DETAILS");

        lblArrivalCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblArrivalCity.setText("Arrival City");

        lblArrivalTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblArrivalTime.setText("Arrival Time");

        lblArrivalBusStn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblArrivalBusStn.setText("Arrival Bus Station");

        lblArrivalBusTer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblArrivalBusTer.setText("Arrival Bus Terminal");

        lblDuration.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDuration.setText("Total Travel Duration");

        lblMiles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMiles.setText("Total Miles");

        javax.swing.GroupLayout arrivalPanelLayout = new javax.swing.GroupLayout(arrivalPanel);
        arrivalPanel.setLayout(arrivalPanelLayout);
        arrivalPanelLayout.setHorizontalGroup(
            arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arrivalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArrivalDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(arrivalPanelLayout.createSequentialGroup()
                        .addComponent(lblArrivalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txtArrivalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(arrivalPanelLayout.createSequentialGroup()
                        .addGroup(arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblArrivalBusStn, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(lblArrivalBusTer, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(lblArrivalTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArrivalBusStn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArrivalBusTer, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, arrivalPanelLayout.createSequentialGroup()
                        .addGroup(arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMiles, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMiles, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addGap(20, 20, 20))
        );

        arrivalPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblArrivalBusStn, lblArrivalBusTer, lblArrivalCity, lblArrivalTime, lblDuration, lblMiles});

        arrivalPanelLayout.setVerticalGroup(
            arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arrivalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblArrivalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArrivalCity)
                    .addComponent(txtArrivalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArrivalTime)
                    .addComponent(txtArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArrivalBusStn)
                    .addComponent(txtArrivalBusStn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArrivalBusTer)
                    .addComponent(txtArrivalBusTer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuration)
                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(arrivalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMiles)
                    .addComponent(txtMiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUpdateBusDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateBusDetails.setText("Update Bus Details");
        btnUpdateBusDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBusDetailsActionPerformed(evt);
            }
        });

        btnDeleteBusDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteBusDetails.setText("Delete Bus Details");
        btnDeleteBusDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBusDetailsActionPerformed(evt);
            }
        });

        panelTitle.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("MANAGE BUS DETAILS");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddBusDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddBusDetails.setText("Add Bus Details");
        btnAddBusDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBusDetailsActionPerformed(evt);
            }
        });

        busTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "From", "To", "Duration", "Miles", "Depart Time", "Arrival Time", "From Bus Station", "To Bus Station", "From Bus Ter", "To Bus Ter", "Company", "Seats", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        busTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(busTable);
        if (busTable.getColumnModel().getColumnCount() > 0) {
            busTable.getColumnModel().getColumn(0).setResizable(false);
            busTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            busTable.getColumnModel().getColumn(1).setResizable(false);
            busTable.getColumnModel().getColumn(1).setPreferredWidth(80);
            busTable.getColumnModel().getColumn(2).setResizable(false);
            busTable.getColumnModel().getColumn(2).setPreferredWidth(80);
            busTable.getColumnModel().getColumn(3).setResizable(false);
            busTable.getColumnModel().getColumn(3).setPreferredWidth(35);
            busTable.getColumnModel().getColumn(4).setResizable(false);
            busTable.getColumnModel().getColumn(4).setPreferredWidth(30);
            busTable.getColumnModel().getColumn(5).setResizable(false);
            busTable.getColumnModel().getColumn(5).setPreferredWidth(45);
            busTable.getColumnModel().getColumn(6).setResizable(false);
            busTable.getColumnModel().getColumn(6).setPreferredWidth(45);
            busTable.getColumnModel().getColumn(7).setResizable(false);
            busTable.getColumnModel().getColumn(7).setPreferredWidth(80);
            busTable.getColumnModel().getColumn(8).setResizable(false);
            busTable.getColumnModel().getColumn(8).setPreferredWidth(80);
            busTable.getColumnModel().getColumn(9).setResizable(false);
            busTable.getColumnModel().getColumn(9).setPreferredWidth(45);
            busTable.getColumnModel().getColumn(10).setResizable(false);
            busTable.getColumnModel().getColumn(10).setPreferredWidth(45);
            busTable.getColumnModel().getColumn(11).setResizable(false);
            busTable.getColumnModel().getColumn(11).setPreferredWidth(80);
            busTable.getColumnModel().getColumn(12).setResizable(false);
            busTable.getColumnModel().getColumn(12).setPreferredWidth(25);
            busTable.getColumnModel().getColumn(13).setResizable(false);
            busTable.getColumnModel().getColumn(13).setPreferredWidth(25);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAddBusDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnUpdateBusDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(btnDeleteBusDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(panelTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(departPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(arrivalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1432, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(departPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arrivalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBusDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateBusDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteBusDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBusDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBusDetailsActionPerformed
        String departureCity = txtDepartureCity.getText();
        String arrivalCity = txtArrivalCity.getText();
        String departureTime = txtDepartureTime.getText();
        String arrivalTime = txtArrivalTime.getText();
        String departureBusTerminal = txtDepartBusTer.getText();
        String arrivalBusTerminal = txtArrivalBusTer.getText();
        String departureBusStation = txtDepartBusStn.getText();
        String arrivalBusStation = txtArrivalBusStn.getText();
        String busCompanyName = txtBusCompany.getText();
        int seats = Integer.parseInt(txtSeats.getText());
        Double price = Double.valueOf(txtPrice.getText());
        int totalMiles = Integer.parseInt(txtMiles.getText());
        String totalDuration = txtDuration.getText();
        
        MySQLUtil.addBusDetails(departureCity, arrivalCity, departureTime, arrivalTime,
                departureBusTerminal, arrivalBusTerminal, departureBusStation,
                arrivalBusStation, busCompanyName, seats, price, totalMiles, totalDuration);
        
        populateTableBusDetails();
        
        clearAllFields();
        
    }//GEN-LAST:event_btnAddBusDetailsActionPerformed

    private void btnUpdateBusDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBusDetailsActionPerformed
        int selectedRow = busTable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to update!");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) busTable.getModel();
        int selectedBusId = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        
//        Bus selectedBus = MySQLUtil.getBusById(selectedBusId);
//        
//        txtDepartureCity.setText(selectedBus.getDepartingCity());
//        txtArrivalCity.setText(selectedBus.getArrivalCity());
//        txtDepartureTime.setText(selectedBus.getDepartingTimestamp());
//        txtArrivalTime.setText(selectedBus.getArrivalTimestamp());
//        txtDepartBusStn.setText(selectedBus.getDepartureBusStation());
//        txtArrivalBusStn.setText(selectedBus.getArrivalBusStation());
//        txtDepartBusTer.setText(selectedBus.getDepartureBusTerminal());
//        txtArrivalBusTer.setText(selectedBus.getArrivalBusTerminal());
//        txtBusCompany.setText(selectedBus.getBusCompanyName());
//        txtDuration.setText(selectedBus.getBusTotalDuration());
//        txtSeats.setText(String.valueOf(selectedBus.getSeats()));
//        txtMiles.setText(String.valueOf(selectedBus.getTotalMiles()));
//        txtPrice.setText(String.valueOf(selectedBus.getPrice()));
        
        String departureCity = txtDepartureCity.getText();
        String arrivalCity = txtArrivalCity.getText();
        String departureTime = txtDepartureTime.getText();
        String arrivalTime = txtArrivalTime.getText();
        String departureBusTerminal = txtDepartBusTer.getText();
        String arrivalBusTerminal = txtArrivalBusTer.getText();
        String departureBusStation = txtDepartBusStn.getText();
        String arrivalBusStation = txtArrivalBusStn.getText();
        String busCompanyName = txtBusCompany.getText();
        int seats = Integer.parseInt(txtSeats.getText());
        Double price = Double.valueOf(txtPrice.getText());
        int totalMiles = Integer.parseInt(txtMiles.getText());
        String totalDuration = txtDuration.getText();
        
        System.out.println(departureBusStation);
        
        MySQLUtil.updateBusDetails(totalDuration, totalMiles, departureTime, arrivalTime,
                departureBusStation, departureBusTerminal, arrivalBusStation,
                arrivalBusTerminal, busCompanyName, seats, price, departureCity,
                arrivalCity, selectedBusId);
        
        clearAllFields();
        populateTableBusDetails();
    }//GEN-LAST:event_btnUpdateBusDetailsActionPerformed
    
    public void clearAllFields() {
        txtDepartureCity.setText("");
        txtArrivalCity.setText("");
        txtDepartureTime.setText("");
        txtArrivalTime.setText("");
        txtDepartBusStn.setText("");
        txtArrivalBusStn.setText("");
        txtDepartBusTer.setText("");
        txtArrivalBusTer.setText("");
        txtBusCompany.setText("");
        txtDuration.setText("");
        txtSeats.setText("");
        txtMiles.setText("");
        txtPrice.setText("");
    }
    
    private void busTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busTableMouseClicked
        int selectedRow = busTable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to update!");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) busTable.getModel();
        int selectedBusId = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        
        Bus selectedBus = MySQLUtil.getBusById(selectedBusId);
        
        txtDepartureCity.setText(selectedBus.getDepartingCity());
        txtArrivalCity.setText(selectedBus.getArrivalCity());
        txtDepartureTime.setText(selectedBus.getDepartingTimestamp());
        txtArrivalTime.setText(selectedBus.getArrivalTimestamp());
        txtDepartBusStn.setText(selectedBus.getDepartureBusStation());
        txtArrivalBusStn.setText(selectedBus.getArrivalBusStation());
        txtDepartBusTer.setText(selectedBus.getDepartureBusTerminal());
        txtArrivalBusTer.setText(selectedBus.getArrivalBusTerminal());
        txtBusCompany.setText(selectedBus.getBusCompanyName());
        txtDuration.setText(selectedBus.getBusTotalDuration());
        txtSeats.setText(String.valueOf(selectedBus.getSeats()));
        txtMiles.setText(String.valueOf(selectedBus.getTotalMiles()));
        txtPrice.setText(String.valueOf(selectedBus.getPrice()));
    }//GEN-LAST:event_busTableMouseClicked

    private void btnDeleteBusDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBusDetailsActionPerformed
        int selectedRow = busTable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete!");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) busTable.getModel();
        int selectedBusId = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        
        MySQLUtil.deleteBusDetails(selectedBusId);
        
        clearAllFields();
        
        populateTableBusDetails();
    }//GEN-LAST:event_btnDeleteBusDetailsActionPerformed
    
    public void populateTableBusDetails() {
        ArrayList<Bus> busList = MySQLUtil.getAllBusDetails();
        
        DefaultTableModel busTableModel = (DefaultTableModel) busTable.getModel();
        busTableModel.setRowCount(0);
        
        for(Bus bus: busList) {
            Object[] row = new Object[14];
            
            row[0] = bus.getBusId();
            row[1] = bus.getDepartingCity();
            row[2] = bus.getArrivalCity();
            row[3] = bus.getBusTotalDuration();
            row[4] = bus.getTotalMiles();
            row[5] = bus.getDepartingTimestamp();
            row[6] = bus.getArrivalTimestamp();
            row[7] = bus.getDepartureBusStation();
            row[8] = bus.getArrivalBusStation();
            row[9] = bus.getDepartureBusTerminal();
            row[10] = bus.getArrivalBusTerminal();
            row[11] = bus.getBusCompanyName();
            row[12] = bus.getSeats();
            row[13] = bus.getPrice();
            
            busTableModel.addRow(row);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBusDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arrivalPanel;
    private javax.swing.JButton btnAddBusDetails;
    private javax.swing.JButton btnDeleteBusDetails;
    private javax.swing.JButton btnUpdateBusDetails;
    private javax.swing.JTable busTable;
    private javax.swing.JPanel departPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblArrivalBusStn;
    private javax.swing.JLabel lblArrivalBusTer;
    private javax.swing.JLabel lblArrivalCity;
    private javax.swing.JLabel lblArrivalDetails;
    private javax.swing.JLabel lblArrivalTime;
    private javax.swing.JLabel lblBusCompany;
    private javax.swing.JLabel lblDepartBusTer;
    private javax.swing.JLabel lblDepartureBusStn;
    private javax.swing.JLabel lblDepartureCity;
    private javax.swing.JLabel lblDepartureDetails;
    private javax.swing.JLabel lblDepartureTime;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblMiles;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JTextField txtArrivalBusStn;
    private javax.swing.JTextField txtArrivalBusTer;
    private javax.swing.JTextField txtArrivalCity;
    private javax.swing.JTextField txtArrivalTime;
    private javax.swing.JTextField txtBusCompany;
    private javax.swing.JTextField txtDepartBusStn;
    private javax.swing.JTextField txtDepartBusTer;
    private javax.swing.JTextField txtDepartureCity;
    private javax.swing.JTextField txtDepartureTime;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtMiles;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSeats;
    // End of variables declaration//GEN-END:variables
}
