/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.busUIPanels;

import java.awt.Color;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.bus.Bus;

/**
 *
 * @author slenk
 */
public class BusSeatSelection extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    boolean toggler1;
    boolean toggler2;
    boolean toggler3;
    boolean toggler4;
    boolean toggler5;
    boolean toggler6;
    boolean toggler7;
    boolean toggler8;
    boolean toggler9;
    boolean toggler10;
    boolean toggler11;
    boolean toggler12;  
    
    int seatCount = 2;
    ArrayList<String> seatsSelected;
    Bus bus;
    String departureDate;
    
    public BusSeatSelection() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.seatsSelected = new ArrayList<>();
    }
    
    public BusSeatSelection(int seatCount, Bus bus, String departureDate) {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.seatCount = seatCount;
        this.seatsSelected = new ArrayList<>();
        this.departureDate = departureDate;
        this.bus = bus;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        seat3 = new javax.swing.JPanel();
        seat4 = new javax.swing.JPanel();
        seat7 = new javax.swing.JPanel();
        seat8 = new javax.swing.JPanel();
        seat11 = new javax.swing.JPanel();
        seat12 = new javax.swing.JPanel();
        seat1 = new javax.swing.JPanel();
        seat2 = new javax.swing.JPanel();
        seat6 = new javax.swing.JPanel();
        seat5 = new javax.swing.JPanel();
        seat10 = new javax.swing.JPanel();
        seat9 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBookSeats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        seat3.setBackground(new java.awt.Color(255, 255, 255));
        seat3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat3Layout = new javax.swing.GroupLayout(seat3);
        seat3.setLayout(seat3Layout);
        seat3Layout.setHorizontalGroup(
            seat3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        seat3Layout.setVerticalGroup(
            seat3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        seat4.setBackground(new java.awt.Color(255, 255, 255));
        seat4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat4Layout = new javax.swing.GroupLayout(seat4);
        seat4.setLayout(seat4Layout);
        seat4Layout.setHorizontalGroup(
            seat4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        seat4Layout.setVerticalGroup(
            seat4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        seat7.setBackground(new java.awt.Color(255, 255, 255));
        seat7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat7Layout = new javax.swing.GroupLayout(seat7);
        seat7.setLayout(seat7Layout);
        seat7Layout.setHorizontalGroup(
            seat7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        seat7Layout.setVerticalGroup(
            seat7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        seat8.setBackground(new java.awt.Color(255, 255, 255));
        seat8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat8Layout = new javax.swing.GroupLayout(seat8);
        seat8.setLayout(seat8Layout);
        seat8Layout.setHorizontalGroup(
            seat8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        seat8Layout.setVerticalGroup(
            seat8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        seat11.setBackground(new java.awt.Color(255, 255, 255));
        seat11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat11Layout = new javax.swing.GroupLayout(seat11);
        seat11.setLayout(seat11Layout);
        seat11Layout.setHorizontalGroup(
            seat11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        seat11Layout.setVerticalGroup(
            seat11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        seat12.setBackground(new java.awt.Color(255, 255, 255));
        seat12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat12Layout = new javax.swing.GroupLayout(seat12);
        seat12.setLayout(seat12Layout);
        seat12Layout.setHorizontalGroup(
            seat12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        seat12Layout.setVerticalGroup(
            seat12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        seat1.setBackground(new java.awt.Color(255, 255, 255));
        seat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat1Layout = new javax.swing.GroupLayout(seat1);
        seat1.setLayout(seat1Layout);
        seat1Layout.setHorizontalGroup(
            seat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        seat1Layout.setVerticalGroup(
            seat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        seat2.setBackground(new java.awt.Color(255, 255, 255));
        seat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat2Layout = new javax.swing.GroupLayout(seat2);
        seat2.setLayout(seat2Layout);
        seat2Layout.setHorizontalGroup(
            seat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        seat2Layout.setVerticalGroup(
            seat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        seat6.setBackground(new java.awt.Color(255, 255, 255));
        seat6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat6Layout = new javax.swing.GroupLayout(seat6);
        seat6.setLayout(seat6Layout);
        seat6Layout.setHorizontalGroup(
            seat6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        seat6Layout.setVerticalGroup(
            seat6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        seat5.setBackground(new java.awt.Color(255, 255, 255));
        seat5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat5Layout = new javax.swing.GroupLayout(seat5);
        seat5.setLayout(seat5Layout);
        seat5Layout.setHorizontalGroup(
            seat5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        seat5Layout.setVerticalGroup(
            seat5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        seat10.setBackground(new java.awt.Color(255, 255, 255));
        seat10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat10Layout = new javax.swing.GroupLayout(seat10);
        seat10.setLayout(seat10Layout);
        seat10Layout.setHorizontalGroup(
            seat10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        seat10Layout.setVerticalGroup(
            seat10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        seat9.setBackground(new java.awt.Color(255, 255, 255));
        seat9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seat9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seat9Layout = new javax.swing.GroupLayout(seat9);
        seat9.setLayout(seat9Layout);
        seat9Layout.setHorizontalGroup(
            seat9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        seat9Layout.setVerticalGroup(
            seat9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(seat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(seat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seat6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(seat9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seat10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(seat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(seat4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(seat11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seat7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seat8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seat12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {seat1, seat2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seat3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seat4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seat7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seat8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seat6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seat11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seat12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seat10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seat9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {seat11, seat3, seat7});

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bus Seat Selection");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        btnBookSeats.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBookSeats.setText("Book Seats");
        btnBookSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnBookSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(btnBookSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seat3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat3MouseClicked
        if(!toggler3) {
            if(seatCount != 0) {
                this.seatCount--;
                System.out.println(seatCount);
                toggler3 = true;
                this.seatsSelected.add("S3");
                seat3.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat3.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat1.removeMouseListener(listener);
                        seat2.removeMouseListener(listener);
                        seat4.removeMouseListener(listener);
                        seat5.removeMouseListener(listener);
                        seat6.removeMouseListener(listener);
                        seat7.removeMouseListener(listener);
                        seat8.removeMouseListener(listener);
                        seat9.removeMouseListener(listener);
                        seat10.removeMouseListener(listener);
                        seat11.removeMouseListener(listener);
                        seat12.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }            
        } else {
            toggler3 = false;
            this.seatsSelected.remove("S3");
            seat3.setBackground(Color.WHITE);
            seatCount++;
            MouseListener[] mouseListeners = seat3.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat1.addMouseListener(listener);
                    seat2.addMouseListener(listener);
                    seat4.addMouseListener(listener);
                    seat5.addMouseListener(listener);
                    seat6.addMouseListener(listener);
                    seat7.addMouseListener(listener);
                    seat8.addMouseListener(listener);
                    seat9.addMouseListener(listener);
                    seat10.addMouseListener(listener);
                    seat11.addMouseListener(listener);
                    seat12.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat3MouseClicked

    private void seat4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat4MouseClicked
        if(!toggler4) {
            if(seatCount != 0) {
                this.seatCount--;
                System.out.println(seatCount);
                toggler4 = true;
                this.seatsSelected.add("S4");
                seat4.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat4.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat1.removeMouseListener(listener);
                        seat2.removeMouseListener(listener);
                        seat3.removeMouseListener(listener);
                        seat5.removeMouseListener(listener);
                        seat6.removeMouseListener(listener);
                        seat7.removeMouseListener(listener);
                        seat8.removeMouseListener(listener);
                        seat9.removeMouseListener(listener);
                        seat10.removeMouseListener(listener);
                        seat11.removeMouseListener(listener);
                        seat12.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }            
        } else {
            toggler4 = false;
            seat4.setBackground(Color.WHITE);
            seatCount++;
            this.seatsSelected.remove("S4");
            MouseListener[] mouseListeners = seat4.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat1.addMouseListener(listener);
                    seat2.addMouseListener(listener);
                    seat3.addMouseListener(listener);
                    seat5.addMouseListener(listener);
                    seat6.addMouseListener(listener);
                    seat7.addMouseListener(listener);
                    seat8.addMouseListener(listener);
                    seat9.addMouseListener(listener);
                    seat10.addMouseListener(listener);
                    seat11.addMouseListener(listener);
                    seat12.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat4MouseClicked

    private void seat7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat7MouseClicked
        if(!toggler7) {
            if(seatCount != 0) {
                this.seatCount--;
                System.out.println(seatCount);
                toggler7 = true;
                this.seatsSelected.add("S7");
                seat7.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat7.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat1.removeMouseListener(listener);
                        seat2.removeMouseListener(listener);
                        seat3.removeMouseListener(listener);
                        seat5.removeMouseListener(listener);
                        seat6.removeMouseListener(listener);
                        seat4.removeMouseListener(listener);
                        seat8.removeMouseListener(listener);
                        seat9.removeMouseListener(listener);
                        seat10.removeMouseListener(listener);
                        seat11.removeMouseListener(listener);
                        seat12.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }            
        } else {
            toggler7 = false;
            seat7.setBackground(Color.WHITE);
            seatCount++;
            this.seatsSelected.remove("S7");
            MouseListener[] mouseListeners = seat7.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat1.addMouseListener(listener);
                    seat2.addMouseListener(listener);
                    seat3.addMouseListener(listener);
                    seat5.addMouseListener(listener);
                    seat6.addMouseListener(listener);
                    seat4.addMouseListener(listener);
                    seat8.addMouseListener(listener);
                    seat9.addMouseListener(listener);
                    seat10.addMouseListener(listener);
                    seat11.addMouseListener(listener);
                    seat12.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat7MouseClicked

    private void seat8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat8MouseClicked
        if(!toggler8) {
            if(seatCount != 0) {
                this.seatCount--;
                this.seatsSelected.add("S8");
                System.out.println(seatCount);
                toggler8 = true;
                seat8.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat8.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat1.removeMouseListener(listener);
                        seat2.removeMouseListener(listener);
                        seat3.removeMouseListener(listener);
                        seat5.removeMouseListener(listener);
                        seat6.removeMouseListener(listener);
                        seat4.removeMouseListener(listener);
                        seat7.removeMouseListener(listener);
                        seat9.removeMouseListener(listener);
                        seat10.removeMouseListener(listener);
                        seat11.removeMouseListener(listener);
                        seat12.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }            
        } else {
            toggler8 = false;
            seat8.setBackground(Color.WHITE);
            seatCount++;
            this.seatsSelected.remove("S8");
            MouseListener[] mouseListeners = seat8.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat1.addMouseListener(listener);
                    seat2.addMouseListener(listener);
                    seat3.addMouseListener(listener);
                    seat5.addMouseListener(listener);
                    seat6.addMouseListener(listener);
                    seat4.addMouseListener(listener);
                    seat7.addMouseListener(listener);
                    seat9.addMouseListener(listener);
                    seat10.addMouseListener(listener);
                    seat11.addMouseListener(listener);
                    seat12.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat8MouseClicked

    private void seat11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat11MouseClicked
        if(!toggler11) {
            if(seatCount != 0) {
                this.seatCount--;
                System.out.println(seatCount);
                toggler11 = true;
                this.seatsSelected.add("S11");
                seat11.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat11.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat1.removeMouseListener(listener);
                        seat2.removeMouseListener(listener);
                        seat3.removeMouseListener(listener);
                        seat5.removeMouseListener(listener);
                        seat6.removeMouseListener(listener);
                        seat4.removeMouseListener(listener);
                        seat7.removeMouseListener(listener);
                        seat9.removeMouseListener(listener);
                        seat10.removeMouseListener(listener);
                        seat8.removeMouseListener(listener);
                        seat12.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }            
        } else {
            toggler11 = false;
            this.seatsSelected.remove("S11");
            seat11.setBackground(Color.WHITE);
            seatCount++;
            MouseListener[] mouseListeners = seat11.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat1.addMouseListener(listener);
                    seat2.addMouseListener(listener);
                    seat3.addMouseListener(listener);
                    seat5.addMouseListener(listener);
                    seat6.addMouseListener(listener);
                    seat4.addMouseListener(listener);
                    seat7.addMouseListener(listener);
                    seat9.addMouseListener(listener);
                    seat10.addMouseListener(listener);
                    seat8.addMouseListener(listener);
                    seat12.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat11MouseClicked

    private void seat12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat12MouseClicked
        if(!toggler12) {
            if(seatCount != 0) {
                this.seatCount--;
                this.seatsSelected.add("S12");
                System.out.println(seatCount);
                toggler12 = true;
                seat12.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat12.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat1.removeMouseListener(listener);
                        seat2.removeMouseListener(listener);
                        seat3.removeMouseListener(listener);
                        seat5.removeMouseListener(listener);
                        seat6.removeMouseListener(listener);
                        seat4.removeMouseListener(listener);
                        seat7.removeMouseListener(listener);
                        seat9.removeMouseListener(listener);
                        seat10.removeMouseListener(listener);
                        seat8.removeMouseListener(listener);
                        seat11.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }            
        } else {
            toggler12 = false;
            seat12.setBackground(Color.WHITE);
            seatCount++;
            this.seatsSelected.remove("S12");
            MouseListener[] mouseListeners = seat12.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat1.addMouseListener(listener);
                    seat2.addMouseListener(listener);
                    seat3.addMouseListener(listener);
                    seat5.addMouseListener(listener);
                    seat6.addMouseListener(listener);
                    seat4.addMouseListener(listener);
                    seat7.addMouseListener(listener);
                    seat9.addMouseListener(listener);
                    seat10.addMouseListener(listener);
                    seat8.addMouseListener(listener);
                    seat11.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat12MouseClicked

    private void seat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat1MouseClicked
        if(!toggler1) {
            if(seatCount != 0) {
                this.seatCount--;
                this.seatsSelected.add("S1");
                System.out.println(seatCount);
                toggler1 = true;
                seat1.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat1.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat12.removeMouseListener(listener);
                        seat2.removeMouseListener(listener);
                        seat3.removeMouseListener(listener);
                        seat5.removeMouseListener(listener);
                        seat6.removeMouseListener(listener);
                        seat4.removeMouseListener(listener);
                        seat7.removeMouseListener(listener);
                        seat9.removeMouseListener(listener);
                        seat10.removeMouseListener(listener);
                        seat8.removeMouseListener(listener);
                        seat11.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }       
        } else {
            toggler1 = false;
            seat1.setBackground(Color.WHITE);
            this.seatsSelected.remove("S1");
            seatCount++;
            MouseListener[] mouseListeners = seat1.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat12.addMouseListener(listener);
                    seat2.addMouseListener(listener);
                    seat3.addMouseListener(listener);
                    seat5.addMouseListener(listener);
                    seat6.addMouseListener(listener);
                    seat4.addMouseListener(listener);
                    seat7.addMouseListener(listener);
                    seat9.addMouseListener(listener);
                    seat10.addMouseListener(listener);
                    seat8.addMouseListener(listener);
                    seat11.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat1MouseClicked

    private void seat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat2MouseClicked
        if(!toggler2) {
            if(seatCount != 0) {
                this.seatCount--;
                this.seatsSelected.add("S2");
                System.out.println(seatCount);
                toggler2 = true;
                seat2.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat2.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat12.removeMouseListener(listener);
                        seat1.removeMouseListener(listener);
                        seat3.removeMouseListener(listener);
                        seat5.removeMouseListener(listener);
                        seat6.removeMouseListener(listener);
                        seat4.removeMouseListener(listener);
                        seat7.removeMouseListener(listener);
                        seat9.removeMouseListener(listener);
                        seat10.removeMouseListener(listener);
                        seat8.removeMouseListener(listener);
                        seat11.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }            
        } else {
            toggler2 = false;
            seat2.setBackground(Color.WHITE);
            seatCount++;
            this.seatsSelected.remove("S2");
            MouseListener[] mouseListeners = seat2.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat12.addMouseListener(listener);
                    seat1.addMouseListener(listener);
                    seat3.addMouseListener(listener);
                    seat5.addMouseListener(listener);
                    seat6.addMouseListener(listener);
                    seat4.addMouseListener(listener);
                    seat7.addMouseListener(listener);
                    seat9.addMouseListener(listener);
                    seat10.addMouseListener(listener);
                    seat8.addMouseListener(listener);
                    seat11.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat2MouseClicked

    private void seat6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat6MouseClicked
        if(!toggler6) {
            if(seatCount != 0) {
                this.seatCount--;
                System.out.println(seatCount);
                toggler6 = true;
                this.seatsSelected.add("S6");
                seat6.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat6.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat12.removeMouseListener(listener);
                        seat1.removeMouseListener(listener);
                        seat3.removeMouseListener(listener);
                        seat5.removeMouseListener(listener);
                        seat2.removeMouseListener(listener);
                        seat4.removeMouseListener(listener);
                        seat7.removeMouseListener(listener);
                        seat9.removeMouseListener(listener);
                        seat10.removeMouseListener(listener);
                        seat8.removeMouseListener(listener);
                        seat11.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }            
        } else {
            toggler6 = false;
            seat6.setBackground(Color.WHITE);
            seatCount++;
            this.seatsSelected.remove("S6");
            MouseListener[] mouseListeners = seat6.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat12.addMouseListener(listener);
                    seat1.addMouseListener(listener);
                    seat3.addMouseListener(listener);
                    seat5.addMouseListener(listener);
                    seat2.addMouseListener(listener);
                    seat4.addMouseListener(listener);
                    seat7.addMouseListener(listener);
                    seat9.addMouseListener(listener);
                    seat10.addMouseListener(listener);
                    seat8.addMouseListener(listener);
                    seat11.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat6MouseClicked

    private void seat5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat5MouseClicked
        if(!toggler5) {
            if(seatCount != 0) {
                this.seatCount--;
                System.out.println(seatCount);
                toggler5 = true;
                this.seatsSelected.add("S5");
                seat5.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat5.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat12.removeMouseListener(listener);
                        seat1.removeMouseListener(listener);
                        seat3.removeMouseListener(listener);
                        seat6.removeMouseListener(listener);
                        seat2.removeMouseListener(listener);
                        seat4.removeMouseListener(listener);
                        seat7.removeMouseListener(listener);
                        seat9.removeMouseListener(listener);
                        seat10.removeMouseListener(listener);
                        seat8.removeMouseListener(listener);
                        seat11.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }            
        } else {
            toggler5 = false;
            seat5.setBackground(Color.WHITE);
            seatCount++;
            this.seatsSelected.remove("S5");
            MouseListener[] mouseListeners = seat5.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat12.addMouseListener(listener);
                    seat1.addMouseListener(listener);
                    seat3.addMouseListener(listener);
                    seat6.addMouseListener(listener);
                    seat2.addMouseListener(listener);
                    seat4.addMouseListener(listener);
                    seat7.addMouseListener(listener);
                    seat9.addMouseListener(listener);
                    seat10.addMouseListener(listener);
                    seat8.addMouseListener(listener);
                    seat11.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat5MouseClicked

    private void seat10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat10MouseClicked
        if(!toggler10) {
            if(seatCount != 0) {
                this.seatCount--;
                System.out.println(seatCount);
                toggler10 = true;
                this.seatsSelected.add("S10");
                seat10.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat10.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat12.removeMouseListener(listener);
                        seat1.removeMouseListener(listener);
                        seat3.removeMouseListener(listener);
                        seat6.removeMouseListener(listener);
                        seat2.removeMouseListener(listener);
                        seat4.removeMouseListener(listener);
                        seat7.removeMouseListener(listener);
                        seat9.removeMouseListener(listener);
                        seat5.removeMouseListener(listener);
                        seat8.removeMouseListener(listener);
                        seat11.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }            
        } else {
            toggler10 = false;
            seat10.setBackground(Color.WHITE);
            seatCount++;
            this.seatsSelected.remove("S10");
            MouseListener[] mouseListeners = seat10.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat12.addMouseListener(listener);
                    seat1.addMouseListener(listener);
                    seat3.addMouseListener(listener);
                    seat6.addMouseListener(listener);
                    seat2.addMouseListener(listener);
                    seat4.addMouseListener(listener);
                    seat7.addMouseListener(listener);
                    seat9.addMouseListener(listener);
                    seat5.addMouseListener(listener);
                    seat8.addMouseListener(listener);
                    seat11.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat10MouseClicked

    private void seat9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seat9MouseClicked
        if(!toggler9) {
            if(seatCount != 0) {
                this.seatCount--;
                this.seatsSelected.add("S9");
                System.out.println(seatCount);
                toggler9 = true;
                seat9.setBackground(Color.BLACK);
                if(seatCount == 0) {
                    MouseListener[] mouseListeners = seat9.getMouseListeners();
                    for(MouseListener listener: mouseListeners) {
                        seat12.removeMouseListener(listener);
                        seat1.removeMouseListener(listener);
                        seat3.removeMouseListener(listener);
                        seat6.removeMouseListener(listener);
                        seat2.removeMouseListener(listener);
                        seat4.removeMouseListener(listener);
                        seat7.removeMouseListener(listener);
                        seat10.removeMouseListener(listener);
                        seat5.removeMouseListener(listener);
                        seat8.removeMouseListener(listener);
                        seat11.removeMouseListener(listener);
                        
                    }
                    JOptionPane.showMessageDialog(this, "Seat selection done!");
                }
            }            
        } else {
            toggler9 = false;
            seat9.setBackground(Color.WHITE);
            seatCount++;
            this.seatsSelected.remove("S9");
            MouseListener[] mouseListeners = seat9.getMouseListeners();
                for(MouseListener listener: mouseListeners) {
                    seat12.addMouseListener(listener);
                    seat1.addMouseListener(listener);
                    seat3.addMouseListener(listener);
                    seat6.addMouseListener(listener);
                    seat2.addMouseListener(listener);
                    seat4.addMouseListener(listener);
                    seat7.addMouseListener(listener);
                    seat10.addMouseListener(listener);
                    seat5.addMouseListener(listener);
                    seat8.addMouseListener(listener);
                    seat11.addMouseListener(listener);

                }
        }
    }//GEN-LAST:event_seat9MouseClicked

    private void btnBookSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookSeatsActionPerformed
        if(!toggler1 && !toggler2 && !toggler3 && !toggler4 && !toggler5
                && !toggler6 && !toggler7 && !toggler8 && !toggler9 
                && !toggler10 && !toggler11 && !toggler12) {
            JOptionPane.showMessageDialog(this, "Please select a seat!");
            return;
        }
        
        System.out.println(this.seatsSelected.toString());
        System.out.println(this.seatsSelected + " " + bus + " " + departureDate);
        
        BusBooking busBooking = new BusBooking(this.seatsSelected, bus, departureDate);
        busBooking.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBookSeatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusSeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusSeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusSeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusSeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusSeatSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookSeats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel seat1;
    private javax.swing.JPanel seat10;
    private javax.swing.JPanel seat11;
    private javax.swing.JPanel seat12;
    private javax.swing.JPanel seat2;
    private javax.swing.JPanel seat3;
    private javax.swing.JPanel seat4;
    private javax.swing.JPanel seat5;
    private javax.swing.JPanel seat6;
    private javax.swing.JPanel seat7;
    private javax.swing.JPanel seat8;
    private javax.swing.JPanel seat9;
    // End of variables declaration//GEN-END:variables
}
