/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HotelUser;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Person.Person;
import mysql.util.MySQLUtil;

/**
 *
 * @author Anshul
 */
public class Checkout extends javax.swing.JPanel {

    /**
     * Creates new form checkoutHotel
     */
    HotelFrame hotelFrame;String city;
    String hotel;
    String address;
    String zipcode;
    int hotelId;
    int userId;
    Date checkin;
    Date checkout;
    int no_rooms;
    int room_no;
    float price;
    long days;
    String roomName;
    float totalPayable = 0;
    int tax = 40;
    
    public Checkout(HotelFrame hotelFrame, String hotel, String address,
            String city, String zipcode, int hotelId, Date checkin, 
            Date checkout, int no_rooms, int room_no, float price,long days, String roomName) {
        initComponents();
        this.hotelFrame = hotelFrame;
        this.hotel = hotel;
        this.address = address;
        this.city =city;
        this.zipcode = zipcode;
        this.hotelId =hotelId;
        this.checkin = checkin;
        this.checkout = checkout;
        this.no_rooms = no_rooms;
        this.room_no = room_no;
        this.price = price;
        this.days = days;
        this.roomName = roomName;
        
        sHotel.setText(hotel);
        sAddress.setText(address);
        sCity.setText(city);
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String formatCheckin = formatter.format(checkin);
        String formatCheckout = formatter.format(checkout);
        
        sIn.setText(String.valueOf(formatCheckin));
        sOut.setText(String.valueOf(formatCheckout));
        
        sRooms.setText(String.valueOf(no_rooms));
        sRooms1.setText(String.valueOf(no_rooms));
        sRooms2.setText(String.valueOf(no_rooms));
        sPrice.setText(String.valueOf(price));
        sRoom.setText(roomName);
        String nights = days + " Nights";
        sDiff.setText(nights);
        sDiff2.setText(String.valueOf(days));
        float totalPrice = price * no_rooms * days;
        sTotal.setText(String.valueOf(totalPrice));
        totalPayable = totalPrice + tax;
        sPay.setText(String.valueOf(totalPayable));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        sDiff = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sRooms = new javax.swing.JLabel();
        sIn = new javax.swing.JLabel();
        sOut = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        x = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        sRooms2 = new javax.swing.JLabel();
        sRoom = new javax.swing.JLabel();
        sHotel = new javax.swing.JLabel();
        sCity = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        sAddress = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g) {

                ImageIcon im = new ImageIcon("D:\\xxxxxx\\git 3\\AED_Final_Project\\AED_Final_Project\\src\\assets\\12.jpg");

                Image i = im.getImage();

                g.drawImage(i, 0, 0, this.getSize().width,
                    this.getSize().height, this);
            }
        };
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        sPay = new javax.swing.JLabel();
        sPrice = new javax.swing.JLabel();
        sRooms1 = new javax.swing.JLabel();
        sDiff2 = new javax.swing.JLabel();
        sTotal = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("HOTEL INFO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 20));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 20, 80));

        jLabel19.setText("ROOMS");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        sDiff.setText("2 Nights");
        jPanel4.add(sDiff, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel21.setText("CHECK-OUT");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        sRooms.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sRooms.setText("1");
        jPanel4.add(sRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 80, 30));

        sIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sIn.setText("12/24/2022");
        jPanel4.add(sIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        sOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sOut.setText("12/26/2022");
        jPanel4.add(sOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 80, 30));

        jLabel22.setText("CHECK-IN");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel24.setText("12:00 PM");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel28.setText("11:00 AM");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 20, 80));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 330, 90));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 239, 239)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setForeground(new java.awt.Color(0, 153, 102));
        jLabel29.setText("Great Choice!");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 310, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("1 Room for 2 Adults");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 30));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 80));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 20, 140));

        x.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        x.setText("x");
        jPanel5.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 10, 30));

        jLabel32.setText("icon");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 30, 30));

        jLabel33.setText("2 Adults");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, 20));

        jLabel34.setForeground(new java.awt.Color(102, 102, 255));
        jLabel34.setText("Free Cancellation!");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, -1));

        jLabel35.setText("Room Only!");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel36.setText("View Cancellation Policy");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 140, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel37.setText("on website.");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 140, -1));

        sRooms2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sRooms2.setText("1");
        jPanel5.add(sRooms2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 10, 30));

        sRoom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sRoom.setText("Standard Room");
        jPanel5.add(sRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 110, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 330, 240));

        sHotel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sHotel.setText("Hotel Name");
        jPanel1.add(sHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 190, -1));

        sCity.setText("hotel address");
        jPanel1.add(sCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 190, 30));

        jLabel5.setBackground(new java.awt.Color(153, 204, 255));
        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setText("Hotel Rating: 4/5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 190, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 330, 10));

        sAddress.setText("hotel address");
        jPanel1.add(sAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, 30));
        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 110));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, 510));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("PRICE SUMMARY");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 10));

        jLabel7.setText("Tax");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel8.setText("No of Rooms");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel9.setText("Days");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 10));

        jLabel10.setText("Room Charges");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Total Payable");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 10));

        jLabel12.setText("Price");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        sPay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sPay.setText("2000");
        jPanel2.add(sPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        sPrice.setText("800");
        jPanel2.add(sPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        sRooms1.setText("1");
        jPanel2.add(sRooms1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        sDiff2.setText("2");
        jPanel2.add(sDiff2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        sTotal.setText("1600");
        jPanel2.add(sTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel18.setText("40");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 220, 250));

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("CHECKOUT");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 580, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("←");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("BOOK HOTEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hotelFrame.switchPanel(new SearchHotel(this.hotelFrame));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String status = "BOOKED";
        
        Person person = MySQLUtil.getPersonSession();
        userId = person.getId();
        System.out.println("userid: -----"+ userId);
        
        MySQLUtil.bookHotel(hotelId, room_no, userId, checkin, checkout, no_rooms, status, 
                totalPayable, tax);
        System.out.println("hotel booked");
        
        JOptionPane.showMessageDialog(this,"Hotel Booked Successfully!");
        this.hotelFrame.switchPanel(new SearchHotel(this.hotelFrame));
         
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel sAddress;
    private javax.swing.JLabel sCity;
    private javax.swing.JLabel sDiff;
    private javax.swing.JLabel sDiff2;
    private javax.swing.JLabel sHotel;
    private javax.swing.JLabel sIn;
    private javax.swing.JLabel sOut;
    private javax.swing.JLabel sPay;
    private javax.swing.JLabel sPrice;
    private javax.swing.JLabel sRoom;
    private javax.swing.JLabel sRooms;
    private javax.swing.JLabel sRooms1;
    private javax.swing.JLabel sRooms2;
    private javax.swing.JLabel sTotal;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
