/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.carRentalAdminPanels;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.CarRental.CarRental;
import mysql.util.MySQLUtil;
/**
 *
 * @author slenk
 */
public class ViewAllCarRentals extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllCarRentals
     */
    public ViewAllCarRentals() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        populateTable();
    }
    
    public void populateTable() {
        ArrayList<CarRental> carRentalList = new 
            ArrayList<>();
        
        carRentalList = MySQLUtil.getAllCarRentalDetails();
        
        DefaultTableModel model = (DefaultTableModel) tableCarRentals.getModel();
        model.setRowCount(0);
        for(CarRental carRental : carRentalList) {
            Object[] row = new Object[9];
            row[0] = carRental.getRentalId();
            row[1] = carRental.getPickupLocation();
            row[2] = carRental.getRatePerHour();
            row[3] = carRental.getMileage();
            row[4] = carRental.getFuelType();
            row[5] = carRental.getSeats();
            row[6] = carRental.getCarType();
            row[7] = carRental.getCarCompany();
            row[8] = carRental.getCarModel();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCarRentals = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View All Car Rentals");

        tableCarRentals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Pickup Location", "Rate Per Hour", "Mileage", "Fuel Type", "Seats", "Car Type", "Car Company", "Car Model"
            }
        ));
        jScrollPane1.setViewportView(tableCarRentals);
        if (tableCarRentals.getColumnModel().getColumnCount() > 0) {
            tableCarRentals.getColumnModel().getColumn(0).setPreferredWidth(20);
            tableCarRentals.getColumnModel().getColumn(1).setPreferredWidth(80);
            tableCarRentals.getColumnModel().getColumn(2).setPreferredWidth(50);
            tableCarRentals.getColumnModel().getColumn(3).setPreferredWidth(45);
            tableCarRentals.getColumnModel().getColumn(4).setPreferredWidth(45);
            tableCarRentals.getColumnModel().getColumn(5).setPreferredWidth(35);
            tableCarRentals.getColumnModel().getColumn(6).setPreferredWidth(45);
            tableCarRentals.getColumnModel().getColumn(7).setPreferredWidth(80);
            tableCarRentals.getColumnModel().getColumn(8).setPreferredWidth(70);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllCarRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllCarRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllCarRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllCarRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllCarRentals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCarRentals;
    // End of variables declaration//GEN-END:variables
}
