/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.carRentalUIPanels;

import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.CarRental.CarRental;
import model.bus.Bus;
import mysql.util.MySQLUtil;
import ui.busUIPanels.BusDisplayUILabels;

/**
 *
 * @author slenk
 */



public class CarSearchDisplay extends javax.swing.JPanel {

    /**
     * Creates new form CarSearchPanel
     */
    
    String pickupLocation;
    String pickupDate;
    String dropoffDate;
    
    public CarSearchDisplay(String pickupLocation, String pickupDate, String dropoffDate) {
        initComponents();
        
        this.pickupLocation = pickupLocation;
        this.pickupDate = pickupDate;
        this.dropoffDate = dropoffDate;
        
        this.setBackground(new Color(1f, 1f, 1f, 0.2f));
        
        populateCarSearchPanel();
    }
    
    public void populateCarSearchPanel() {
        
        ArrayList<CarRental> carRentalSearchList = 
                MySQLUtil.searchCarRentalsByPickupLocation(pickupLocation);
        
        System.out.println(carRentalSearchList.size());
        
        setLayout(new GridLayout(carRentalSearchList.size(), 3, 0, 0));     
        
        for(CarRental carRental: carRentalSearchList) {
            
            for (int j=0; j<3; j++) {
                JLabel lbl = new JLabel();
                if(j == 0) {
                    lbl.setText("Car Image");
                }
                else if(j == 1) {
                    lbl.setText(RentDisplayUILabels.getRentalDetailsHTML(
                            carRental.getPickupLocation()
                            , carRental.getMileage(), carRental.getFuelType(),
                            carRental.getSeats(), carRental.getCarType(), 
                            carRental.getCarCompany(), 
                            carRental.getCarModel()));
                } else {
                    lbl.setText(
                            RentDisplayUILabels.getRentalPriceHTML(carRental.getRatePerHour()));
                    Component comp = this;
                    lbl.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
//                            JOptionPane.showMessageDialog("clicked");
                            CarBookingFrame carBookingFrame =
                                    new CarBookingFrame(carRental);
                            carBookingFrame.setVisible(true);
                        }
                    });
                }
                lbl.setBorder(BorderFactory.createLineBorder(Color.BLACK));
                this.add(lbl); 
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
