/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.carRentalUIPanels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mysql.util.MySQLUtil;
import static mysql.util.MySQLUtil.connectMySQL;
import ui.flightUIPanels.SelectInsurance;

/**
 *
 * @author slenk
 */
public class MyCarRentalBookings extends javax.swing.JFrame {

    /**
     * Creates new form MyCarRentalBookings
     */
    public MyCarRentalBookings() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        populateTable();
    }
    
    public void populateTable() {
        int personId = MySQLUtil.getPersonSession().getId();
        String query = "select fb.bookingId, f.carCompany, f.carModel, f.pickupLocation, fb.bookingDate,\n" +
"f.fuelType, f.mileage, f.carType, f.seats, fb.price,\n" +
"fb.bookingStatus, fb.insuranceStatus \n" +
"from car_rentals_bookings fb inner join car_rentals f on f.rentalId =\n" +
" fb.rentalId inner join person p on p.id = fb.personId where fb.personId=?";
        
        DefaultTableModel model = (DefaultTableModel) tableMyFlightBookings.getModel();
        model.setRowCount(0);
        
        try {
            Connection conn = connectMySQL();
            
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, personId);
            
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()) {
                Object[] row = new Object[13];
                row[0] = rs.getString("bookingId");
                row[1] = rs.getString("carCompany") + " " + rs.getString("carModel");
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(new Date(rs.getString("bookingDate")));
                calendar.add(Calendar.HOUR_OF_DAY, 24);
//                System.out.println(calendar.getTime());
                
//                System.out.println();
                row[2] = rs.getString("pickupLocation");
                row[3] = rs.getString("pickupLocation");
                row[4] = rs.getString("bookingDate");
                row[5] = rs.getString("bookingDate");
                row[6] = rs.getString("fuelType");
                row[7] = rs.getString("mileage");
                row[8] = rs.getString("carType");
                row[9] = rs.getString("seats");
                row[10] = rs.getString("price");
                row[11] = rs.getString("bookingStatus");
                row[12] = rs.getString("insuranceStatus");
                model.addRow(row);
            }
                        
        } catch (SQLException ex) {
            Logger.getLogger(MySQLUtil.class.getName()).log(Level.SEVERE, "Issue with "
                    + "get flights query!", ex);
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMyFlightBookings = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnCheckin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Car Rental Bookings");

        tableMyFlightBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Car ", "Pickup", "Drop Off", "Booking Date", "Return Date", "Fuel Type", "Mileage", "Car Type", "Seats", "Price", "Status", "Insurance Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableMyFlightBookings);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Insurance Details");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnCheckin.setBackground(new java.awt.Color(0, 204, 204));
        btnCheckin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCheckin.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckin.setText("Check In");
        btnCheckin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckinActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(436, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(74, 74, 74)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(133, 133, 133))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(216, 216, 216)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckinActionPerformed
        int selectedRow = tableMyFlightBookings.getSelectedRow();

        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a booking!");
            return;
        }

        int selectedBookingId = Integer.parseInt(tableMyFlightBookings.getModel()
            .getValueAt(selectedRow, 0).toString());

        String selectedStatus = tableMyFlightBookings.getModel()
        .getValueAt(selectedRow, 11).toString();

        if(selectedStatus.equals("CHECKED_IN")) {
            JOptionPane.showMessageDialog(this, "You are already checked in!");
        }
        
        if(tableMyFlightBookings.getModel()
                .getValueAt(selectedRow, 12) == null) {
            JOptionPane.showMessageDialog(this, "Please select an insurance!");
            return;
        }
        
        if(tableMyFlightBookings.getModel()
                .getValueAt(selectedRow, 12).equals("PENDING")) {
            JOptionPane.showMessageDialog(this, "Please wait for insurance approval for checkin!");
            return;
        }
        
        if(tableMyFlightBookings.getModel()
                .getValueAt(selectedRow, 12).equals("REJECTED")) {
            JOptionPane.showMessageDialog(this, "Sorry for the inconvinence,"
                    + " booking not insured. Money would be refunded in your account in 3-5 business days!");
            return;
        }
        
        MySQLUtil.updateCarBookingStatus(selectedBookingId, "CHECKED_IN");

        populateTable();
    }//GEN-LAST:event_btnCheckinActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = tableMyFlightBookings.getSelectedRow();
        
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a booking!");
            return;
        }
        
        String selectedStatus = tableMyFlightBookings.getModel()
                .getValueAt(selectedRow, 11).toString();
        
        if(selectedStatus.equals("CHECKED_IN")) {
            JOptionPane.showMessageDialog(this, "You are already checked in!");
            return;
        }
        
        if(tableMyFlightBookings.getModel()
                .getValueAt(selectedRow, 12) != null) {
            if(tableMyFlightBookings.getModel()
                .getValueAt(selectedRow, 12).toString().equals("PENDING")) {
                JOptionPane.showMessageDialog(this, "Wait for insurance approval!");
                return;
            }
            if(tableMyFlightBookings.getModel()
                .getValueAt(selectedRow, 12).toString().equals("APPROVED")) {
                JOptionPane.showMessageDialog(this, "You're insured!");
                return;
            }
        }
        
        int bookingId = Integer.parseInt(tableMyFlightBookings.getModel()
                .getValueAt(selectedRow, 0).toString());
        
        double totalPrice = Double.valueOf(tableMyFlightBookings.getModel()
                .getValueAt(selectedRow, 10).toString());
        
        SelectCarInsurance s = new SelectCarInsurance(bookingId, totalPrice);
        s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCarRentalBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCarRentalBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCarRentalBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCarRentalBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCarRentalBookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMyFlightBookings;
    // End of variables declaration//GEN-END:variables
}
