/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.flightAdminDashboard;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Flight.Flight;
import mysql.util.MySQLUtil;

/**
 *
 * @author slenk
 */
public class ActiveFlightsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ActiveFlightsPanel
     */
    public ActiveFlightsPanel() {
        initComponents();
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tableActiveFlights.getModel();
        
        model.setRowCount(0);
        
        ArrayList<Flight> activeFlightList = 
                MySQLUtil.getAllActiveFlights();
        
        for(Flight flight : activeFlightList) {
            Object[] row = new Object[16];
            
            row[0] = flight.getFlightId();
            row[1] = flight.getTotalFlightDuration();
            row[2] = flight.getTotalMiles();
            row[3] = flight.getDepartingTimeStamp();
            row[4] = flight.getArrivalTimeStamp();
            row[5] = flight.getDepartureAirport();
            row[6] = flight.getDepartureTerminal();
            row[7] = flight.getArrivalAirport();
            row[8] = flight.getArrivalTerminal();
            row[9] = flight.getFlightCompanyCode();
            row[10] = flight.getFlightCompanyName();
            row[11] = flight.getFlightType();
            row[12] = flight.getSeats();
            row[13] = flight.getDepartingCity();
            row[14] = flight.getArrivalCity();
            row[15] = flight.getPrice();
            
            model.addRow(row);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableActiveFlights = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACTIVE FLIGHTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        tableActiveFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Duration", "Miles", "Departing Time", "Arrival Time", "Departure Airport", "Departure Terminal", "Arrival Airport", "Arrival Terminal", "Company Code", "Company", "Flight Type", "Seats", "Departure City", "Arrival City", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableActiveFlights);
        if (tableActiveFlights.getColumnModel().getColumnCount() > 0) {
            tableActiveFlights.getColumnModel().getColumn(0).setPreferredWidth(15);
            tableActiveFlights.getColumnModel().getColumn(1).setPreferredWidth(35);
            tableActiveFlights.getColumnModel().getColumn(2).setPreferredWidth(35);
            tableActiveFlights.getColumnModel().getColumn(3).setPreferredWidth(75);
            tableActiveFlights.getColumnModel().getColumn(4).setPreferredWidth(55);
            tableActiveFlights.getColumnModel().getColumn(5).setPreferredWidth(55);
            tableActiveFlights.getColumnModel().getColumn(6).setPreferredWidth(75);
            tableActiveFlights.getColumnModel().getColumn(7).setPreferredWidth(75);
            tableActiveFlights.getColumnModel().getColumn(8).setPreferredWidth(50);
            tableActiveFlights.getColumnModel().getColumn(9).setPreferredWidth(75);
            tableActiveFlights.getColumnModel().getColumn(10).setPreferredWidth(55);
            tableActiveFlights.getColumnModel().getColumn(11).setPreferredWidth(55);
            tableActiveFlights.getColumnModel().getColumn(12).setPreferredWidth(55);
            tableActiveFlights.getColumnModel().getColumn(13).setPreferredWidth(75);
            tableActiveFlights.getColumnModel().getColumn(14).setPreferredWidth(75);
            tableActiveFlights.getColumnModel().getColumn(15).setPreferredWidth(45);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableActiveFlights;
    // End of variables declaration//GEN-END:variables
}
