/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.flightAdminDashboard;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Flight.Flight;
import mysql.util.MySQLUtil;
import ui.RestrauntUser.RestrauntFrame;
import ui.RestrauntUser.RestrauntList;
/**
 *
 * @author Anshul
 */
public class OrderFlightFood extends javax.swing.JPanel {

    /**
     * Creates new form OrderFlightFood
     */
    int extraId;
    String city;
    String extraType;
    FlightAdminDashboard flightAdminDashboard;
    RestrauntFrame restrauntFrame;
    
    public OrderFlightFood() {
        initComponents();
        populateTable();
    }
    
    public OrderFlightFood(FlightAdminDashboard flightAdminDashboard) {
        initComponents();
        populateTable();
        
        this.flightAdminDashboard = flightAdminDashboard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        sCity1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFlightData = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 102));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 140, 40));

        sCity1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "New York", "Chicago" }));
        sCity1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102)));
        jPanel1.add(sCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 320, 50));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Location");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 60, 50));

        tableFlightData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Departing Time", "Arrival Time", "Company Code", "Company", "Flight Type", "Departure City", "Arrival City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableFlightData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 560, 190));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 580, 380));

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ORDER FOOD FOR FLIGHTS");
        jPanel2.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Discover the best food & drinks with us!");
        jPanel2.add(jLabel1);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 580, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tableFlightData.getSelectedRow();
         
        if(selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this,"Please select a row to view.");
            return;
        }
          
        DefaultTableModel model = (DefaultTableModel) tableFlightData.getModel();
        extraId = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
        city = sCity1.getSelectedItem().toString();
        extraType = "flight";
        
        this.flightAdminDashboard.switchPanel(new RestrauntList(this.flightAdminDashboard, city, extraId, extraType));
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tableFlightData.getModel();
        
        model.setRowCount(0);
        
        ArrayList<Flight> activeFlightList = 
                MySQLUtil.getAllFlightData();
        
        for(Flight flight : activeFlightList) {
            Object[] row = new Object[10];
            
            row[0] = flight.getFlightId();
            row[1] = flight.getTotalFlightDuration();
            row[2] = flight.getTotalMiles();
            row[3] = flight.getDepartingTimeStamp();
            row[4] = flight.getArrivalTimeStamp();
            row[5] = flight.getFlightCompanyCode();
            row[6] = flight.getFlightCompanyName();
            row[7] = flight.getFlightType();
            row[8] = flight.getDepartingCity();
            row[9]= flight.getArrivalCity();
            
            model.addRow(row);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> sCity1;
    private javax.swing.JTable tableFlightData;
    // End of variables declaration//GEN-END:variables
}
