/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HotelBookings;

/**
 *
 * @author Anshul
 */
public class BookingAdmin extends javax.swing.JPanel {

    /**
     * Creates new form BookingAdmin
     */
    public BookingAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room No", "Passenger", "from", "to", "No of Rooms"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 580, 250));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Bookings");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 600, 30));

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 150, 30));
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 200, 30));
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 200, 30));

        jLabel15.setText("From");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 20));

        jLabel16.setText("Passenger");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, 20));

        jLabel17.setText("To");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, 20));
        add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 200, 30));

        jLabel19.setText("Room No");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 20));
        add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 200, 30));
        add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 200, 30));

        jLabel18.setText("Rooms");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 20));

        jLabel20.setText("Status");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, 20));
        add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 200, 30));

        jLabel21.setText("No of");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
