/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RestrauntUser;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Person.Person;
import mysql.util.MySQLUtil;
import static mysql.util.MySQLUtil.connectMySQL;

/**
 *
 * @author Anshul
 */
public class TableBooking extends javax.swing.JPanel {

    /**
     * Creates new form TableBooking
     */
    RestrauntFrame restrauntFrame;
    String city;String restraunt; 
    String address;
    String zipcode;
    int restrauntId;
    int table_no;
    
    public TableBooking(RestrauntFrame restrauntFrame, String city, String restraunt, 
            String address, String zipcode, int restrauntId) {
        initComponents();
        this.restrauntFrame = restrauntFrame;
        this.city = city;
        this.restraunt =restraunt;
        this.address = address;
        this.zipcode =zipcode;
        this.restrauntId =restrauntId;
    }
    
    public TableBooking(RestrauntFrame restrauntFrame) {
        initComponents();
        this.restrauntFrame = restrauntFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crAP = new javax.swing.JComboBox<>();
        crTime = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sDate = new com.toedter.calendar.JDateChooser();
        sAP = new javax.swing.JComboBox<>();
        sTime = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        crAP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        jLabel23.setText("Time");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Table");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 50));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("←");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 280, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Book A Table: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        jLabel3.setText("Date");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 250, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 290, 180));

        jPanel5.setBackground(new java.awt.Color(255, 0, 102));
        jPanel5.setForeground(new java.awt.Color(255, 0, 102));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ORDER");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 70, 280, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Photo");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, 60));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, 100));

        jPanel6.setBackground(new java.awt.Color(255, 0, 102));
        jPanel6.setForeground(new java.awt.Color(255, 0, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("BOOK TABLE");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 70, 280, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Photo");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, 60));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 80, -1, 100));
        add(sDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 252, 180, 30));

        sAP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        add(sAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 70, 30));
        add(sTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 110, 30));

        jLabel24.setText("Time");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 50, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
//        book tabel
        int userId;
        Person person = MySQLUtil.getPersonSession();
        userId = person.getId();
        String user = MySQLUtil.getAllPersonName(userId);
        System.out.println("userid: -----"+ userId);
        if(sTime.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inputs should not be Empty");
            return;
        }
          
        int time = 0;
        if(sAP.getSelectedItem().toString().equals("AM")) time = Integer.parseInt(sTime.getText());
        if(sAP.getSelectedItem().toString().equals("PM")) time = Integer.parseInt(sTime.getText()) + 12;
        if(time == 24) time = 0;
        
        Date date = sDate.getDate();
        LocalDate dateFormat = LocalDate.of(2022, date.getMonth(),date.getDate());
        LocalTime timeFormat = LocalTime.of(time, 0, 0);
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");  
        
        LocalDateTime localDateTime = LocalDateTime.of(dateFormat, timeFormat);
        String dtf2 = dtf.format(localDateTime);
        String status = "BOOKED";
        getTable();
        
        MySQLUtil.addTableBookings(table_no, status, dtf2, restrauntId, restraunt, userId, user);
        
        JOptionPane.showMessageDialog(this, "Record created successfully!");
        
        sDate.setDate(null);
        sTime.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        this.restrauntFrame.switchPanel(new RestrauntMenu(this.restrauntFrame));
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.restrauntFrame.switchPanel(new RestrauntMenu(this.restrauntFrame));
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.restrauntFrame.switchPanel(new RestrauntMenu(this.restrauntFrame));
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.restrauntFrame.switchPanel(new RestrauntList(this.restrauntFrame));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void getTable() {
        String query = "Select t.table_no from tables t inner join table_bookings tb on t.restrauntId = tb.restrauntId where t.restrauntId = ? and (t.status = 'AVAILABLE' or tb.status = 'AVAILABLE') LIMIT 1";
         try {
            Connection conn = connectMySQL();
            PreparedStatement ps = conn.prepareStatement(query); 
            
            ps.setInt(1,restrauntId);
            
            ResultSet rs = ps.executeQuery();   
            
            if(rs.next()){
                table_no = rs.getInt("table_no");
            }
        } catch (SQLException ex) {
            Logger.getLogger(MySQLUtil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> crAP;
    private javax.swing.JTextField crTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox<String> sAP;
    private com.toedter.calendar.JDateChooser sDate;
    private javax.swing.JTextField sTime;
    // End of variables declaration//GEN-END:variables
}
